### ISSUE TITLE
capn: command not found

### ISSUE THREAD

**Issue by kcolton** [thatguystone/cog#1]
I ran this on my command line:

`$ capn crunch`

and got

`bash: capn: command not found`

Do I have to install anything? Brand new macbook pro

**Comment by adamJLev** [comment]
+1 Yeah guyz this no working for me. Is cog short for corgi dog?

**Comment by thatguystone** [comment]
Uhh, so I don't know what a macbook is, but you really should be trying this on a computer. Books don't work. I'm using Vesta, and it works for me. Maybe try this: on your big-mac :hamburger:, get a good brew going :beers: and install special sauce. If that doesn't work, I've heard that people have had luck running it on ajax and HTML5. So maybe try that.

**Comment by thatguystone** [comment]
@adamJLev It's very insensitive to make fun of how short corgis are. They know they're short. You don't have to rub it in.

![You made him sad](https://cloud.githubusercontent.com/assets/921573/10709191/0c3beaa8-79f1-11e5-934e-3f863eba2b21.jpg)

Now apologize to that poor, poor corgi!

**Comment by kcolton** [comment]
![image](https://cloud.githubusercontent.com/assets/390961/18837694/bb979bfa-83d2-11e6-8adc-da9ce61863ae.png)
